config/routes.rb
GrantBlog::Application.routes.draw do
  get "admin/index"

  namespace :admin do
    get '/' => 'admin#index'
    post '/login' => 'admin#login'
    get '/logout' => 'admin#logout'
    resources :blogs
    resources :blog_templates do
      get 'get_content', on: :collection
    end
    resources :blog_cats
  end

  root 'blogs#index'

  resources :blogs
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  belongs_to :blog_template
  belongs_to :blog_cat
  accepts_nested_attributes_for :blog_template
  accepts_nested_attributes_for :blog_cat
  default_scope {order('created_at DESC')}
end

app/models/blog_cat.rb
class BlogCat < ActiveRecord::Base
  has_many :blogs
  default_scope {order('sort ASC')}
end

app/models/blog_template.rb
class BlogTemplate < ActiveRecord::Base
  has_many :blogs
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password(validations: false)
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  layout "application"
  def index
    if session["user_id"]
      redirect_to admin_blogs_path
    else
      render '/admin/login'
    end
  end

  def login
    @user_name = params[:user_name]
    if User.find_by(name: params[:user_name], role: "admin").try(
                    :authenticate, params[:user_password])
      session["user_id"] = @user_name
      redirect_to admin_blogs_path
    else
      render '/admin/login'
    end
  end

  def logout
    reset_session
    redirect_to admin_path
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  inherit_resources
  layout "admin"

  before_filter :auth_logined?

  private

  def auth_logined?
    redirect_to "/admin" unless session["user_id"]
  end

end

app/controllers/admin/blog_cats_controller.rb
class Admin::BlogCatsController < Admin::BaseController

  def permitted_params
    params.permit(:blog_cat => [:title, :cat_type, :sort])
  end

  def show
    redirect_to admin_blog_cats_path
  end
end

app/controllers/admin/blog_templates_controller.rb
class Admin::BlogTemplatesController < Admin::BaseController
  def permitted_params
    params.permit(:blog_template => [:title, :content])
  end

  def show
    redirect_to admin_blog_templates_path
  end

  def get_content
    blog_content = BlogTemplate.find(params[:id])
    render text: blog_content.content
  end
end

app/controllers/admin/blogs_controller.rb
class Admin::BlogsController < Admin::BaseController

  before_filter :load_blog_templates, only: [:new, :edit]
  before_filter :load_blog_cats, only: [:new, :edit]

  def permitted_params
    params.permit(:blog => [:title, :blog_template_id, :blog_cat_id, :content])
  end

  def new
    @blog = Blog.new
    @blog.build_blog_template
    @blog.build_blog_cat
  end

  def index
    @blogs = Blog.paginate(:page => params[:page], :per_page => 30)
  end

  def show
    redirect_to admin_blogs_path
  end

  private

  def load_blog_templates
    @blog_templates = BlogTemplate.all
  end

  def load_blog_cats
    @blog_cats = BlogCat.all
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  before_filter :load_blog_cats
  layout "blogs"

  private

  def load_blog_cats
    @blog_cats = BlogCat.all
  end
end

app/controllers/blogs_controller.rb
class BlogsController < BaseController
  def index
    if params[:cat_id]
      @blogs = Blog.where(blog_cat_id: params[:cat_id]).paginate(:page => params[:page], :per_page => 30)
    else
      @blogs = Blog.paginate(:page => params[:page], :per_page => 30)
    end
  end

  def show
    @blog = Blog.find(params[:id])
    @blog.view_count = @blog.view_count + 1
    @blog.save
  end
end

app/helpers/admin/blog_tabs_helper.rb
module Admin::BlogTabsHelper
  def show_cat_type(cat_type)
    cat_type == "list" ? "文章列表" : "单篇文章"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def admin_tabs_class(controller)
    params[:controller] == controller ? "active" : ""
  end

  def format_date_time(date_time)
    date_time.strftime("%Y-%m-%d %H:%M:%S")
  end

  def tabs_class(controller, cat_id=nil)
    (params[:controller] == controller &&
      ((params[:cat_id].nil? && cat_id.nil?) ||
        params[:cat_id] == cat_id.to_s)) ? "active" : ""
  end
end

app/views/admin/blog_cats/_form.html.haml
= form_for [:admin, @blog_cat] do |f|
  %div.row
    %div.large-6
      %div.row
        %div.columns.large-2
          = f.label :title, "名字", class: "right inline required"
        %div.columns.large-10
          = f.text_field :title
    %div.large-6
      %div.row
        %div.columns.large-2
          = f.label :cat_type, "类型", class: "right inline"
        %div.columns.large-4.left
          = f.select :cat_type, [['文章列表', "list"], ['单篇文章', "single"]]
    %div.large-6
      %div.row
        %div.columns.large-2
          = f.label :sort, "排序", class: "right inline"
        %div.columns.large-2.left
          = f.text_field :sort
  %div.row
    .div.large-6
      = f.submit '保存', class: "button small radius"

app/views/admin/blog_cats/edit.html.haml
%div.row
  %h3.page-title 编辑板块
= render "form"

app/views/admin/blog_cats/index.html.haml
%div.row
  =link_to "新建板块", new_admin_blog_cat_path, class: "button small radius"

%div.row
  %table
    %thead
      %tr
        %th 名字
        %th 类型
        %th 排序
        %th 动作
    %tbody
      - @blog_cats.each do |blog_cat|
        %tr
          %td{width: "200"}
            = blog_cat.title
          %td{width: "200"}
            = show_cat_type(blog_cat.cat_type)
          %td{width: "100"}
            = blog_cat.sort
          %td{width: "200"}
            =link_to "编辑", edit_admin_blog_cat_path(blog_cat), class: "margin_right_10"
            = "|"
            =link_to "删除", admin_blog_cat_path(blog_cat), method: "delete", confirm: "你确认删除吗？", class: "margin_left_10"

app/views/admin/blog_cats/new.html.haml
%div.row
  %h3.page-title 新建板块
= render "form"

app/views/admin/blog_templates/_form.html.haml
= form_for [:admin, @blog_template] do |f|
  %div.row
    %div.large-12
      %div.row
        %div.columns.large-1
          = f.label :title, "名字", class: "right inline required"
        %div.columns.large-8.left
          = f.text_field :title
    %div.large-12.content_div
      %div.row
        %div.columns.large-1
          = f.label :content, "模板内容", class: "right inline"
        %div.columns.large-10.left.template_content
          %dl.sub-nav.editor_nav
            %dd.active
              = link_to "编辑", "javascript:void(0)", id: "blog_template_edit"
            %dd
              = link_to "预览", "javascript:void(0)", id: "blog_template_preview"
          = f.text_area :content
        %div.columns.large-10.left.template_preview.hide

  %div.row
    .div.large-6
      = f.submit '保存博客模板', class: "button small radius"

app/views/admin/blog_templates/edit.html.haml
%div.row
  %h3.page-title 编辑模板
= render "form"

app/views/admin/blog_templates/index.html.haml
%div.row
  =link_to "新建模板", new_admin_blog_template_path, class: "button small radius"

%div.row
  %table
    %thead
      %tr
        %th 名字
        %th 动作
    %tbody
      - @blog_templates.each do |blog_template|
        %tr
          %td{width: "200"}
            = blog_template.title
          %td{width: "200"}
            =link_to "编辑", edit_admin_blog_template_path(blog_template), class: "margin_right_10"
            = "|"
            =link_to "删除", admin_blog_template_path(blog_template), method: "delete", confirm: "你确认删除吗？", class: "margin_left_10"

app/views/admin/blog_templates/new.html.haml
%div.row
  %h3.page-title 新建博客模板
= render "form"

app/views/admin/blogs/_form.html.haml
= form_for [:admin, @blog] do |f|
  %div.row
    %div.large-12
      %div.row
        %div.columns.large-1
          = f.label :title, "标题", class: "right inline required"
        %div.columns.large-8.left
          = f.text_field :title
    - if @blog.id.nil?
      %div.large-12
        %div.row
          %div.columns.large-1
            = f.label :title, "文章模板", class: "right inline required"
          %div.columns.large-2.left
            = f.select :blog_template_id, @blog_templates.map{|x|[x.title, x.id]}
    %div.large-12
      %div.row
        %div.columns.large-1
          = f.label :title, "文章板块", class: "right inline required"
        %div.columns.large-2.left
          = f.select :blog_cat_id, @blog_cats.map{|x|[x.title, x.id]}
    %div.large-12.content_div
      %div.row
        %div.columns.large-1
          = f.label :content, "文章内容", class: "right inline"
        %div.columns.large-10.left.blog_content
          %dl.sub-nav.editor_nav
            %dd.active
              = link_to "编辑", "javascript:void(0)", id: "blog_edit"
            %dd
              = link_to "预览", "javascript:void(0)", id: "blog_preview"
          = f.text_area :content
        %div.columns.large-10.left.blog_preview.hide

  %div.row
    .div.large-6
      = f.submit '保存文章', class: "button small radius"

app/views/admin/blogs/edit.html.haml
%div.row
  %h3.page-title 编辑文章
= render "form"

app/views/admin/blogs/index.html.haml
%div.row
  =link_to "新建文章", new_admin_blog_path, class: "button small radius"

%div.row
  %table
    %thead
      %tr
        %th 标题
        %th 内容
        %th 创建时间
        %th 更新时间
        %th 动作
    %tbody
      - @blogs.each do |blog|
        %tr
          %td{width: "200"}
            = truncate(blog.title, length: 30)
          %td{width: "400"}
            = truncate(blog.content, length: 50)
          %td{width: "220"}
            = format_date_time blog.created_at
          %td{width: "220"}
            = format_date_time blog.updated_at
          %td{width: "200"}
            =link_to "编辑", edit_admin_blog_path(blog), class: "margin_right_10"
            = "|"
            =link_to "删除", admin_blog_path(blog), method: "delete", confirm: "你确认删除吗？", class: "margin_left_10"

%div.row
  = will_paginate @blogs

app/views/admin/blogs/new.html.haml
%div.row
  %h3.page-title 新建文章
= render "form"

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

app/views/admin/login.html.haml
- provide(:title, '博客后台登录')
%div.row
  %h1.center 博客后台登录

%form.login-in{action: "/admin/login", method: "post"}
  %div.row
    %div.small-5.center
      %div.row
        %div.small-3.columns
          %label.right.inline 用户名
        %div.small-9.columns
          %input{type: "text", name: "user_name", value: "#{@user_name}"}
      %div.row
        %div.small-3.columns
          %label.right.inline 密码
        %div.small-9.columns
          %input{type: "password", name: "user_password"}
      %div.row
        %div.small-12.columns
          %input{type: "hidden", name: "authenticity_token", value: "#{form_authenticity_token}"}
          %input.button.small.right{type: "submit", value: "登录"}

app/views/admin/shared/_nav.html.haml
%div.row
  %h1 博客后台管理
  = link_to "登出", "/admin/logout", class: "right inline small button logout"
%div.row
  %section.top-bar-section
    %nav.top-bar
      %ul.left
        %li{:class => admin_tabs_class("admin/blogs")}
          = link_to "文章管理", admin_blogs_path
        %li{:class => admin_tabs_class("admin/blog_templates")}
          = link_to "文章模板管理", admin_blog_templates_path
        %li{:class => admin_tabs_class("admin/blog_cats")}
          = link_to "文章板块管理", admin_blog_cats_path

app/views/blogs/index.html.haml
%div.row
  %table.blog_list
    - @blogs.each do |blog|
      = render 'shared/blog_preview', blog: blog

%div.row
  = will_paginate @blogs

app/views/blogs/show.html.haml
%div.row
  %h4.blog_title
    = @blog.title
= text_area_tag "blog_content", @blog.content, class: "hide"
%div.row.blog_content_preview

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "博客后台管理" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'admin/shared/nav'%>
    <div class="body_main">
      <%= yield %>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Grant的博客" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="body_main">
      <%= yield %>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/blogs.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="chinaz-site-verification" content="04c0faeb-23b2-4879-b255-63e5f8848626" />

    <title><%= content_for?(:title) ? yield(:title) : "Grant的博客" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <div class="body_main">
      <%= yield %>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
<% if Rails.env == "production"%>
  <script type="text/javascript" src="http://js.tongji.linezing.com/656426/tongji.js"></script><noscript><a href="http://www.linezing.com"><img src="http://img.tongji.linezing.com/656426/tongji.gif"/></a></noscript>
<% end %>
</html>

app/views/shared/_blog_preview.html.haml
%tr
  %td
    = link_to blog.title, blog_path(blog)
    %div.blog_bottom
      %i.fi-plus
      = "创建于:"
      = format_date_time blog.created_at
      %span.right
        %span.view_count
          %i.fi-eye
          = "浏览数: #{blog.view_count}"
        %span.comment_count
          %i.fi-comment
          = "评论数: #{blog.comment_count}"

app/views/shared/_nav.html.haml
%div.row
  %h1 Grant's Blog
%div.row
  %section.top-bar-section
    %nav.top-bar
      %ul.left
        %li{:class => tabs_class("blogs")}
          = link_to "主页", root_path
        - @blog_cats.each do |blog_cat|
          %li{:class => tabs_class("blogs", blog_cat.id)}
            = link_to blog_cat.title, "#{blogs_path}?cat_id=#{blog_cat.id}"